const path = require("path");

const FONT_DIR = path.join(__dirname, "..", "assets", "fonts");

function f(file) {
  return path.join(FONT_DIR, file);
}

// A large, curated library of bundled, open-license (OFL/Apache) fonts —
// not literally every Google Font (1,800+ families would be gigabytes and
// an unusable dropdown), but a wide, organized spread across every major
// style so there's a good fit for almost any banner. Bundling the actual
// .ttf files (instead of relying on whatever happens to be installed on
// the host) means banners render identically on every machine this app
// runs on. Add more here any time — just drop the .ttf into assets/fonts
// and add an entry below.
const FONTS = {
  // ---------------- Sans-serif (clean / modern) ----------------
  "poppins-bold": { label: "Poppins Bold (modern, bold)", family: "Poppins", weight: "bold", style: "normal", file: f("Poppins-Bold.ttf") },
  "poppins-regular": { label: "Poppins Regular (clean, modern)", family: "Poppins", weight: "normal", style: "normal", file: f("Poppins-Regular.ttf") },
  "roboto-bold": { label: "Roboto Bold (Google's workhorse sans)", family: "Roboto", weight: "bold", style: "normal", file: f("Roboto.ttf") },
  "opensans-bold": { label: "Open Sans Bold (friendly, readable)", family: "Open Sans", weight: "bold", style: "normal", file: f("OpenSans-Bold.ttf") },
  "lato-bold": { label: "Lato Bold (warm, humanist)", family: "Lato", weight: "bold", style: "normal", file: f("Lato-Bold.ttf") },
  "inter-bold": { label: "Inter Bold (crisp, UI-native)", family: "Inter", weight: "bold", style: "normal", file: f("Inter.ttf") },
  "nunito-bold": { label: "Nunito Bold (soft, rounded)", family: "Nunito", weight: "bold", style: "normal", file: f("Nunito.ttf") },
  "raleway-bold": { label: "Raleway Bold (elegant sans)", family: "Raleway", weight: "bold", style: "normal", file: f("Raleway.ttf") },
  "worksans-bold": { label: "Work Sans Bold (grotesque, versatile)", family: "Work Sans", weight: "bold", style: "normal", file: f("WorkSans.ttf") },
  "rubik-bold": { label: "Rubik Bold (rounded corners)", family: "Rubik", weight: "bold", style: "normal", file: f("Rubik.ttf") },
  "manrope-bold": { label: "Manrope Bold (modern geometric)", family: "Manrope", weight: "bold", style: "normal", file: f("Manrope.ttf") },
  "dmsans-bold": { label: "DM Sans Bold (low-contrast geometric)", family: "DM Sans", weight: "bold", style: "normal", file: f("DMSans.ttf") },
  "karla-bold": { label: "Karla Bold (grotesque, friendly)", family: "Karla", weight: "bold", style: "normal", file: f("Karla.ttf") },
  "mulish-bold": { label: "Mulish Bold (minimalist sans)", family: "Mulish", weight: "bold", style: "normal", file: f("Mulish.ttf") },
  "barlow-bold": { label: "Barlow Bold (slightly condensed)", family: "Barlow", weight: "bold", style: "normal", file: f("Barlow.ttf") },
  "sourcesans-bold": { label: "Source Sans Bold (Adobe's UI sans)", family: "Source Sans 3", weight: "bold", style: "normal", file: f("SourceSans3.ttf") },
  "notosans-bold": { label: "Noto Sans Bold (broad language support)", family: "Noto Sans", weight: "bold", style: "normal", file: f("NotoSans.ttf") },
  "archivo-bold": { label: "Archivo Bold (grotesque, sturdy)", family: "Archivo", weight: "bold", style: "normal", file: f("Archivo.ttf") },
  "outfit-bold": { label: "Outfit Bold (contemporary geometric)", family: "Outfit", weight: "bold", style: "normal", file: f("Outfit.ttf") },
  "spacegrotesk-bold": { label: "Space Grotesk Bold (techy, proportional)", family: "Space Grotesk", weight: "bold", style: "normal", file: f("SpaceGrotesk.ttf") },
  "josefinsans-bold": { label: "Josefin Sans Bold (geometric, vintage)", family: "Josefin Sans", weight: "bold", style: "normal", file: f("JosefinSans.ttf") },
  questrial: { label: "Questrial (light geometric)", family: "Questrial", weight: "normal", style: "normal", file: f("Questrial-Regular.ttf") },
  "exo2-bold": { label: "Exo 2 Bold (futuristic geometric)", family: "Exo 2", weight: "bold", style: "normal", file: f("Exo2.ttf") },
  "montserrat-bold": { label: "Montserrat Bold (modern geometric)", family: "Montserrat", weight: "bold", style: "normal", file: f("Montserrat.ttf") },
  "quicksand-bold": { label: "Quicksand Bold (friendly, rounded)", family: "Quicksand", weight: "bold", style: "normal", file: f("Quicksand.ttf") },

  // ---------------- Serif (elegant / editorial) ----------------
  "playfair-bold": { label: "Playfair Display (elegant serif)", family: "Playfair Display", weight: "bold", style: "normal", file: f("PlayfairDisplay.ttf") },
  "lora-bold": { label: "Lora Bold (classic serif)", family: "Lora", weight: "bold", style: "normal", file: f("Lora.ttf") },
  "merriweather-bold": { label: "Merriweather Bold (readable serif)", family: "Merriweather", weight: "bold", style: "normal", file: f("Merriweather.ttf") },
  "cormorant-semibold": { label: "Cormorant Garamond (refined, elegant)", family: "Cormorant Garamond", weight: "600", style: "normal", file: f("CormorantGaramond.ttf") },
  "ptserif-bold": { label: "PT Serif Bold (transitional serif)", family: "PT Serif", weight: "bold", style: "normal", file: f("PTSerif-Bold.ttf") },
  "notoserif-bold": { label: "Noto Serif Bold (broad language support)", family: "Noto Serif", weight: "bold", style: "normal", file: f("NotoSerif.ttf") },
  "crimsontext-bold": { label: "Crimson Text Bold (book-style serif)", family: "Crimson Text", weight: "bold", style: "normal", file: f("CrimsonText-Bold.ttf") },
  "librebaskerville-bold": { label: "Libre Baskerville Bold (classic book serif)", family: "Libre Baskerville", weight: "bold", style: "normal", file: f("LibreBaskerville.ttf") },
  "ebgaramond-bold": { label: "EB Garamond Bold (timeless Garamond)", family: "EB Garamond", weight: "bold", style: "normal", file: f("EBGaramond.ttf") },
  "bitter-bold": { label: "Bitter Bold (slab serif)", family: "Bitter", weight: "bold", style: "normal", file: f("Bitter.ttf") },
  "domine-bold": { label: "Domine Bold (sturdy serif)", family: "Domine", weight: "bold", style: "normal", file: f("Domine.ttf") },
  "vollkorn-bold": { label: "Vollkorn Bold (warm text serif)", family: "Vollkorn", weight: "bold", style: "normal", file: f("Vollkorn.ttf") },
  "spectral-bold": { label: "Spectral Bold (crisp editorial serif)", family: "Spectral", weight: "bold", style: "normal", file: f("Spectral-Bold.ttf") },
  "cardo-bold": { label: "Cardo Bold (classical serif)", family: "Cardo", weight: "bold", style: "normal", file: f("Cardo-Bold.ttf") },

  // ---------------- Display / decorative (posters, headlines) ----------------
  "bebas-neue": { label: "Bebas Neue (tall poster display)", family: "Bebas Neue", weight: "normal", style: "normal", file: f("BebasNeue-Regular.ttf") },
  anton: { label: "Anton (ultra-bold condensed)", family: "Anton", weight: "normal", style: "normal", file: f("Anton-Regular.ttf") },
  "oswald-bold": { label: "Oswald Bold (condensed, sturdy)", family: "Oswald", weight: "bold", style: "normal", file: f("Oswald.ttf") },
  alfaslabone: { label: "Alfa Slab One (chunky slab)", family: "Alfa Slab One", weight: "normal", style: "normal", file: f("AlfaSlabOne-Regular.ttf") },
  "passionone-bold": { label: "Passion One Bold (rounded impact)", family: "Passion One", weight: "bold", style: "normal", file: f("PassionOne-Bold.ttf") },
  fjallaone: { label: "Fjalla One (compact display)", family: "Fjalla One", weight: "normal", style: "normal", file: f("FjallaOne-Regular.ttf") },
  righteous: { label: "Righteous (rounded, retro-futuristic)", family: "Righteous", weight: "normal", style: "normal", file: f("Righteous-Regular.ttf") },
  bungee: { label: "Bungee (bold urban display)", family: "Bungee", weight: "normal", style: "normal", file: f("Bungee-Regular.ttf") },
  abrilfatface: { label: "Abril Fatface (high-contrast display serif)", family: "Abril Fatface", weight: "normal", style: "normal", file: f("AbrilFatface-Regular.ttf") },
  lobster: { label: "Lobster (bold retro script)", family: "Lobster", weight: "normal", style: "normal", file: f("Lobster-Regular.ttf") },
  "comfortaa-bold": { label: "Comfortaa Bold (rounded geometric)", family: "Comfortaa", weight: "bold", style: "normal", file: f("Comfortaa.ttf") },
  "baloo2-bold": { label: "Baloo 2 Bold (playful rounded)", family: "Baloo 2", weight: "bold", style: "normal", file: f("Baloo2.ttf") },
  "fredoka-bold": { label: "Fredoka Bold (bubbly, friendly)", family: "Fredoka", weight: "bold", style: "normal", file: f("Fredoka.ttf") },

  // ---------------- Script / handwriting (festive, personal) ----------------
  "dancing-script": { label: "Dancing Script (festive cursive)", family: "Dancing Script", weight: "normal", style: "normal", file: f("DancingScript.ttf") },
  pacifico: { label: "Pacifico (fun script)", family: "Pacifico", weight: "normal", style: "normal", file: f("Pacifico-Regular.ttf") },
  "great-vibes": { label: "Great Vibes (elegant signature script)", family: "Great Vibes", weight: "normal", style: "normal", file: f("GreatVibes-Regular.ttf") },
  sacramento: { label: "Sacramento (delicate script)", family: "Sacramento", weight: "normal", style: "normal", file: f("Sacramento-Regular.ttf") },
  "caveat-bold": { label: "Caveat (handwritten, bold)", family: "Caveat", weight: "bold", style: "normal", file: f("Caveat.ttf") },
  satisfy: { label: "Satisfy (casual brush script)", family: "Satisfy", weight: "normal", style: "normal", file: f("Satisfy-Regular.ttf") },
  "kalam-bold": { label: "Kalam Bold (handwritten, warm)", family: "Kalam", weight: "bold", style: "normal", file: f("Kalam-Bold.ttf") },
  shadowsintolight: { label: "Shadows Into Light (light handwriting)", family: "Shadows Into Light", weight: "normal", style: "normal", file: f("ShadowsIntoLight.ttf") },
  indieflower: { label: "Indie Flower (bubbly handwriting)", family: "Indie Flower", weight: "normal", style: "normal", file: f("IndieFlower-Regular.ttf") },
  "amaticsc-bold": { label: "Amatic SC Bold (tall, hand-drawn)", family: "Amatic SC", weight: "bold", style: "normal", file: f("AmaticSC-Bold.ttf") },
  permanentmarker: { label: "Permanent Marker (thick marker pen)", family: "Permanent Marker", weight: "normal", style: "normal", file: f("PermanentMarker-Regular.ttf") },
  courgette: { label: "Courgette (smooth casual script)", family: "Courgette", weight: "normal", style: "normal", file: f("Courgette-Regular.ttf") },
  parisienne: { label: "Parisienne (flowing French script)", family: "Parisienne", weight: "normal", style: "normal", file: f("Parisienne-Regular.ttf") },
  yellowtail: { label: "Yellowtail (bold brush script)", family: "Yellowtail", weight: "normal", style: "normal", file: f("Yellowtail-Regular.ttf") },
  allura: { label: "Allura (delicate calligraphy)", family: "Allura", weight: "normal", style: "normal", file: f("Allura-Regular.ttf") },
  "tangerine-bold": { label: "Tangerine Bold (classic calligraphy)", family: "Tangerine", weight: "bold", style: "normal", file: f("Tangerine-Bold.ttf") },
  homemadeapple: { label: "Homemade Apple (natural handwriting)", family: "Homemade Apple", weight: "normal", style: "normal", file: f("HomemadeApple-Regular.ttf") },
  marckscript: { label: "Marck Script (warm cursive)", family: "Marck Script", weight: "normal", style: "normal", file: f("MarckScript-Regular.ttf") },
  pinyonscript: { label: "Pinyon Script (formal invitation script)", family: "Pinyon Script", weight: "normal", style: "normal", file: f("PinyonScript-Regular.ttf") },
  playball: { label: "Playball (bold single-stroke script)", family: "Playball", weight: "normal", style: "normal", file: f("Playball-Regular.ttf") },
  cookie: { label: "Cookie (playful brush script)", family: "Cookie", weight: "normal", style: "normal", file: f("Cookie-Regular.ttf") },
  handlee: { label: "Handlee (casual handwriting)", family: "Handlee", weight: "normal", style: "normal", file: f("Handlee-Regular.ttf") },
  patrickhand: { label: "Patrick Hand (neat handwriting)", family: "Patrick Hand", weight: "normal", style: "normal", file: f("PatrickHand-Regular.ttf") },
  damion: { label: "Damion (elegant brush script)", family: "Damion", weight: "normal", style: "normal", file: f("DamionRegular.ttf") },

  // ---------------- Monospace (technical, retro-typewriter) ----------------
  "robotomono-bold": { label: "Roboto Mono Bold (clean monospace)", family: "Roboto Mono", weight: "bold", style: "normal", file: f("RobotoMono.ttf") },
  "spacemono-bold": { label: "Space Mono Bold (retro-futuristic mono)", family: "Space Mono", weight: "bold", style: "normal", file: f("SpaceMono-Bold.ttf") },
  "jetbrainsmono-bold": { label: "JetBrains Mono Bold (developer mono)", family: "JetBrains Mono", weight: "bold", style: "normal", file: f("JetBrainsMono.ttf") },
  "courierprime-bold": { label: "Courier Prime Bold (typewriter)", family: "Courier Prime", weight: "bold", style: "normal", file: f("CourierPrime-Bold.ttf") },

  // ---------------- More: Sans-serif ----------------
  "abel": { label: "Abel (sans-serif)", family: "Abel", weight: "normal", style: "normal", file: f("Abel-Regular.ttf") },
  "actor": { label: "Actor (sans-serif)", family: "Actor", weight: "normal", style: "normal", file: f("Actor-Regular.ttf") },
  "alata": { label: "Alata (sans-serif)", family: "Alata", weight: "normal", style: "normal", file: f("Alata-Regular.ttf") },
  "aldrich": { label: "Aldrich (sans-serif)", family: "Aldrich", weight: "normal", style: "normal", file: f("Aldrich-Regular.ttf") },
  "alegreyasans-bold": { label: "Alegreya Sans Bold (sans-serif)", family: "Alegreya Sans", weight: "bold", style: "normal", file: f("AlegreyaSans-Bold.ttf") },
  "allerta": { label: "Allerta (sans-serif)", family: "Allerta", weight: "normal", style: "normal", file: f("Allerta-Regular.ttf") },
  "allertastencil": { label: "Allerta Stencil (sans-serif)", family: "Allerta Stencil", weight: "normal", style: "normal", file: f("AllertaStencil-Regular.ttf") },
  "amaranth-bold": { label: "Amaranth Bold (sans-serif)", family: "Amaranth", weight: "bold", style: "normal", file: f("Amaranth-Bold.ttf") },
  "andika-bold": { label: "Andika Bold (sans-serif)", family: "Andika", weight: "bold", style: "normal", file: f("Andika-Bold.ttf") },
  "antic": { label: "Antic (sans-serif)", family: "Antic", weight: "normal", style: "normal", file: f("Antic-Regular.ttf") },
  "barlowcondensed-bold": { label: "Barlow Condensed Bold (sans-serif)", family: "Barlow Condensed", weight: "bold", style: "normal", file: f("BarlowCondensed-Bold.ttf") },
  "barlowsemicondensed-bold": { label: "Barlow Semi Condensed Bold (sans-serif)", family: "Barlow Semi Condensed", weight: "bold", style: "normal", file: f("BarlowSemiCondensed-Bold.ttf") },
  "bayon": { label: "Bayon (sans-serif)", family: "Bayon", weight: "normal", style: "normal", file: f("Bayon-Regular.ttf") },
  "bevietnampro-bold": { label: "Be Vietnam Pro Bold (sans-serif)", family: "Be Vietnam Pro", weight: "bold", style: "normal", file: f("BeVietnamPro-Bold.ttf") },
  "cabincondensed-bold": { label: "Cabin Condensed Bold (sans-serif)", family: "Cabin Condensed", weight: "bold", style: "normal", file: f("CabinCondensed-Bold.ttf") },
  "cagliostro": { label: "Cagliostro (sans-serif)", family: "Cagliostro", weight: "normal", style: "normal", file: f("Cagliostro-Regular.ttf") },
  "candal": { label: "Candal (sans-serif)", family: "Candal", weight: "normal", style: "normal", file: f("Candal.ttf") },
  "cantarell-bold": { label: "Cantarell Bold (sans-serif)", family: "Cantarell", weight: "bold", style: "normal", file: f("Cantarell-Bold.ttf") },
  "carme": { label: "Carme (sans-serif)", family: "Carme", weight: "normal", style: "normal", file: f("Carme-Regular.ttf") },
  "convergence": { label: "Convergence (sans-serif)", family: "Convergence", weight: "normal", style: "normal", file: f("Convergence-Regular.ttf") },
  "daysone": { label: "Days One (sans-serif)", family: "Days One", weight: "normal", style: "normal", file: f("DaysOne-Regular.ttf") },
  "didactgothic": { label: "Didact Gothic (sans-serif)", family: "Didact Gothic", weight: "normal", style: "normal", file: f("DidactGothic-Regular.ttf") },
  "dorsa": { label: "Dorsa (sans-serif)", family: "Dorsa", weight: "normal", style: "normal", file: f("Dorsa-Regular.ttf") },
  "electrolize": { label: "Electrolize (sans-serif)", family: "Electrolize", weight: "normal", style: "normal", file: f("Electrolize-Regular.ttf") },
  "federo": { label: "Federo (sans-serif)", family: "Federo", weight: "normal", style: "normal", file: f("Federo-Regular.ttf") },
  "firasans-bold": { label: "Fira Sans Bold (sans-serif)", family: "Fira Sans", weight: "bold", style: "normal", file: f("FiraSans-Bold.ttf") },
  "firasanscondensed-bold": { label: "Fira Sans Condensed Bold (sans-serif)", family: "Fira Sans Condensed", weight: "bold", style: "normal", file: f("FiraSansCondensed-Bold.ttf") },
  "firasansextracondensed-bold": { label: "Fira Sans Extra Condensed Bold (sans-serif)", family: "Fira Sans Extra Condensed", weight: "bold", style: "normal", file: f("FiraSansExtraCondensed-Bold.ttf") },
  "francoisone": { label: "Francois One (sans-serif)", family: "Francois One", weight: "normal", style: "normal", file: f("FrancoisOne-Regular.ttf") },
  "geo": { label: "Geo (sans-serif)", family: "Geo", weight: "normal", style: "normal", file: f("Geo-Regular.ttf") },
  "gfsneohellenic-bold": { label: "GFS Neohellenic Bold (sans-serif)", family: "GFS Neohellenic", weight: "bold", style: "normal", file: f("GFSNeohellenicBold.ttf") },
  "gothica1-bold": { label: "Gothic A1 Bold (sans-serif)", family: "Gothic A1", weight: "bold", style: "normal", file: f("GothicA1-Bold.ttf") },
  "hammersmithone": { label: "Hammersmith One (sans-serif)", family: "Hammersmith One", weight: "normal", style: "normal", file: f("HammersmithOne-Regular.ttf") },
  "hind-bold": { label: "Hind Bold (sans-serif)", family: "Hind", weight: "bold", style: "normal", file: f("Hind-Bold.ttf") },
  "istokweb-bold": { label: "Istok Web Bold (sans-serif)", family: "Istok Web", weight: "bold", style: "normal", file: f("IstokWeb-Bold.ttf") },
  "jockeyone": { label: "Jockey One (sans-serif)", family: "Jockey One", weight: "normal", style: "normal", file: f("JockeyOne-Regular.ttf") },
  "kanit-bold": { label: "Kanit Bold (sans-serif)", family: "Kanit", weight: "bold", style: "normal", file: f("Kanit-Bold.ttf") },
  "livvic-bold": { label: "Livvic Bold (sans-serif)", family: "Livvic", weight: "bold", style: "normal", file: f("Livvic-Bold.ttf") },
  "mako": { label: "Mako (sans-serif)", family: "Mako", weight: "normal", style: "normal", file: f("Mako-Regular.ttf") },
  "marvel-bold": { label: "Marvel Bold (sans-serif)", family: "Marvel", weight: "bold", style: "normal", file: f("Marvel-Bold.ttf") },
  "metrophobic": { label: "Metrophobic (sans-serif)", family: "Metrophobic", weight: "normal", style: "normal", file: f("Metrophobic-Regular.ttf") },
  "michroma": { label: "Michroma (sans-serif)", family: "Michroma", weight: "normal", style: "normal", file: f("Michroma-Regular.ttf") },
  "molengo": { label: "Molengo (sans-serif)", family: "Molengo", weight: "normal", style: "normal", file: f("Molengo-Regular.ttf") },
  "moulpali": { label: "Moulpali (sans-serif)", family: "Moulpali", weight: "normal", style: "normal", file: f("Moulpali-Regular.ttf") },
  "mukta-bold": { label: "Mukta Bold (sans-serif)", family: "Mukta", weight: "bold", style: "normal", file: f("Mukta-Bold.ttf") },
  "newscycle-bold": { label: "News Cycle Bold (sans-serif)", family: "News Cycle", weight: "bold", style: "normal", file: f("NewsCycle-Bold.ttf") },
  "nobile-bold": { label: "Nobile Bold (sans-serif)", family: "Nobile", weight: "bold", style: "normal", file: f("Nobile-Bold.ttf") },
  "numans": { label: "Numans (sans-serif)", family: "Numans", weight: "normal", style: "normal", file: f("Numans-Regular.ttf") },
  "oxygen-bold": { label: "Oxygen Bold (sans-serif)", family: "Oxygen", weight: "bold", style: "normal", file: f("Oxygen-Bold.ttf") },
  "paytoneone": { label: "Paytone One (sans-serif)", family: "Paytone One", weight: "normal", style: "normal", file: f("PaytoneOne-Regular.ttf") },
  "philosopher-bold": { label: "Philosopher Bold (sans-serif)", family: "Philosopher", weight: "bold", style: "normal", file: f("Philosopher-Bold.ttf") },
  "play-bold": { label: "Play Bold (sans-serif)", family: "Play", weight: "bold", style: "normal", file: f("Play-Bold.ttf") },
  "preahvihear": { label: "Preahvihear (sans-serif)", family: "Preahvihear", weight: "normal", style: "normal", file: f("Preahvihear-Regular.ttf") },
  "prompt-bold": { label: "Prompt Bold (sans-serif)", family: "Prompt", weight: "bold", style: "normal", file: f("Prompt-Bold.ttf") },
  "ptsans-bold": { label: "PT Sans Bold (sans-serif)", family: "PT Sans", weight: "bold", style: "normal", file: f("PT_Sans-Web-Bold.ttf") },
  "ptsanscaption-bold": { label: "PT Sans Caption Bold (sans-serif)", family: "PT Sans Caption", weight: "bold", style: "normal", file: f("PT_Sans-Caption-Web-Bold.ttf") },
  "ptsansnarrow-bold": { label: "PT Sans Narrow Bold (sans-serif)", family: "PT Sans Narrow", weight: "bold", style: "normal", file: f("PT_Sans-Narrow-Web-Bold.ttf") },
  "puritan-bold": { label: "Puritan Bold (sans-serif)", family: "Puritan", weight: "bold", style: "normal", file: f("Puritan-Bold.ttf") },
  "rajdhani-bold": { label: "Rajdhani Bold (sans-serif)", family: "Rajdhani", weight: "bold", style: "normal", file: f("Rajdhani-Bold.ttf") },
  "rationale": { label: "Rationale (sans-serif)", family: "Rationale", weight: "normal", style: "normal", file: f("Rationale-Regular.ttf") },
  "russoone": { label: "Russo One (sans-serif)", family: "Russo One", weight: "normal", style: "normal", file: f("RussoOne-Regular.ttf") },
  "sarabun-bold": { label: "Sarabun Bold (sans-serif)", family: "Sarabun", weight: "bold", style: "normal", file: f("Sarabun-Bold.ttf") },
  "secularone": { label: "Secular One (sans-serif)", family: "Secular One", weight: "normal", style: "normal", file: f("SecularOne-Regular.ttf") },
  "shanti": { label: "Shanti (sans-serif)", family: "Shanti", weight: "normal", style: "normal", file: f("Shanti-Regular.ttf") },
  "signikanegativesc-bold": { label: "Signika Negative SC Bold (sans-serif)", family: "Signika Negative SC", weight: "bold", style: "normal", file: f("SignikaNegativeSC-Bold.ttf") },
  "sixcaps": { label: "Six Caps (sans-serif)", family: "Six Caps", weight: "normal", style: "normal", file: f("SixCaps.ttf") },
  "snippet": { label: "Snippet (sans-serif)", family: "Snippet", weight: "normal", style: "normal", file: f("Snippet.ttf") },
  "spinnaker": { label: "Spinnaker (sans-serif)", family: "Spinnaker", weight: "normal", style: "normal", file: f("Spinnaker-Regular.ttf") },
  "tajawal-bold": { label: "Tajawal Bold (sans-serif)", family: "Tajawal", weight: "bold", style: "normal", file: f("Tajawal-Bold.ttf") },
  "tenorsans": { label: "Tenor Sans (sans-serif)", family: "Tenor Sans", weight: "normal", style: "normal", file: f("TenorSans-Regular.ttf") },
  "titilliumweb-bold": { label: "Titillium Web Bold (sans-serif)", family: "Titillium Web", weight: "bold", style: "normal", file: f("TitilliumWeb-Bold.ttf") },
  "varela": { label: "Varela (sans-serif)", family: "Varela", weight: "normal", style: "normal", file: f("Varela-Regular.ttf") },
  "varelaround": { label: "Varela Round (sans-serif)", family: "Varela Round", weight: "normal", style: "normal", file: f("VarelaRound-Regular.ttf") },
  "voltaire": { label: "Voltaire (sans-serif)", family: "Voltaire", weight: "normal", style: "normal", file: f("Voltaire-Regular.ttf") },
  "wireone": { label: "Wire One (sans-serif)", family: "Wire One", weight: "normal", style: "normal", file: f("WireOne-Regular.ttf") },

  // ---------------- More: Serif ----------------
  "abhayalibre-bold": { label: "Abhaya Libre Bold (serif)", family: "Abhaya Libre", weight: "bold", style: "normal", file: f("AbhayaLibre-Bold.ttf") },
  "alice": { label: "Alice (serif)", family: "Alice", weight: "normal", style: "normal", file: f("Alice-Regular.ttf") },
  "amiri-bold": { label: "Amiri Bold (serif)", family: "Amiri", weight: "bold", style: "normal", file: f("Amiri-Bold.ttf") },
  "artifika": { label: "Artifika (serif)", family: "Artifika", weight: "normal", style: "normal", file: f("Artifika-Regular.ttf") },
  "arvo-bold": { label: "Arvo Bold (serif)", family: "Arvo", weight: "bold", style: "normal", file: f("Arvo-Bold.ttf") },
  "bentham": { label: "Bentham (serif)", family: "Bentham", weight: "normal", style: "normal", file: f("Bentham-Regular.ttf") },
  "bevan": { label: "Bevan (serif)", family: "Bevan", weight: "normal", style: "normal", file: f("Bevan-Regular.ttf") },
  "brawler-bold": { label: "Brawler Bold (serif)", family: "Brawler", weight: "bold", style: "normal", file: f("Brawler-Bold.ttf") },
  "breeserif": { label: "Bree Serif (serif)", family: "Bree Serif", weight: "normal", style: "normal", file: f("BreeSerif-Regular.ttf") },
  "cantataone": { label: "Cantata One (serif)", family: "Cantata One", weight: "normal", style: "normal", file: f("CantataOne-Regular.ttf") },
  "caudex-bold": { label: "Caudex Bold (serif)", family: "Caudex", weight: "bold", style: "normal", file: f("Caudex-Bold.ttf") },
  "copse": { label: "Copse (serif)", family: "Copse", weight: "normal", style: "normal", file: f("Copse-Regular.ttf") },
  "cormorantsc-bold": { label: "Cormorant SC Bold (serif)", family: "Cormorant SC", weight: "bold", style: "normal", file: f("CormorantSC-Bold.ttf") },
  "creteround": { label: "Crete Round (serif)", family: "Crete Round", weight: "normal", style: "normal", file: f("CreteRound-Regular.ttf") },
  "dmserifdisplay": { label: "DM Serif Display (serif)", family: "DM Serif Display", weight: "normal", style: "normal", file: f("DMSerifDisplay-Regular.ttf") },
  "dmseriftext": { label: "DM Serif Text (serif)", family: "DM Serif Text", weight: "normal", style: "normal", file: f("DMSerifText-Regular.ttf") },
  "gfsdidot": { label: "GFS Didot (serif)", family: "GFS Didot", weight: "normal", style: "normal", file: f("GFSDidot-Regular.ttf") },
  "gildadisplay": { label: "Gilda Display (serif)", family: "Gilda Display", weight: "normal", style: "normal", file: f("GildaDisplay-Regular.ttf") },
  "goudybookletter1911": { label: "Goudy Bookletter 1911 (serif)", family: "Goudy Bookletter 1911", weight: "normal", style: "normal", file: f("GoudyBookletter1911.ttf") },
  "holtwoodonesc": { label: "Holtwood One SC (serif)", family: "Holtwood One SC", weight: "normal", style: "normal", file: f("HoltwoodOneSC-Regular.ttf") },
  "ibmplexserif-bold": { label: "IBM Plex Serif Bold (serif)", family: "IBM Plex Serif", weight: "bold", style: "normal", file: f("IBMPlexSerif-Bold.ttf") },
  "imfelldoublepica": { label: "IM Fell Double Pica (serif)", family: "IM Fell Double Pica", weight: "normal", style: "normal", file: f("IMFELLDoublePica-Regular.ttf") },
  "imfelldoublepicasc": { label: "IM Fell Double Pica SC (serif)", family: "IM Fell Double Pica SC", weight: "normal", style: "normal", file: f("IMFeDPsc28P.ttf") },
  "imfelldwpica": { label: "IM Fell DW Pica (serif)", family: "IM Fell DW Pica", weight: "normal", style: "normal", file: f("IMFePIrm28P.ttf") },
  "imfelldwpicasc": { label: "IM Fell DW Pica SC (serif)", family: "IM Fell DW Pica SC", weight: "normal", style: "normal", file: f("IMFePIsc28P.ttf") },
  "imfellenglish": { label: "IM Fell English (serif)", family: "IM Fell English", weight: "normal", style: "normal", file: f("IMFeENrm28P.ttf") },
  "imfellenglishsc": { label: "IM Fell English SC (serif)", family: "IM Fell English SC", weight: "normal", style: "normal", file: f("IMFeENsc28P.ttf") },
  "imfellfrenchcanon": { label: "IM Fell French Canon (serif)", family: "IM Fell French Canon", weight: "normal", style: "normal", file: f("IMFeFCrm28P.ttf") },
  "imfellfrenchcanonsc": { label: "IM Fell French Canon SC (serif)", family: "IM Fell French Canon SC", weight: "normal", style: "normal", file: f("IMFeFCsc28P.ttf") },
  "imfellgreatprimer": { label: "IM Fell Great Primer (serif)", family: "IM Fell Great Primer", weight: "normal", style: "normal", file: f("IMFeGPrm28P.ttf") },
  "imfellgreatprimersc": { label: "IM Fell Great Primer SC (serif)", family: "IM Fell Great Primer SC", weight: "normal", style: "normal", file: f("IMFeGPsc28P.ttf") },
  "judson-bold": { label: "Judson Bold (serif)", family: "Judson", weight: "bold", style: "normal", file: f("Judson-Bold.ttf") },
  "lusitana-bold": { label: "Lusitana Bold (serif)", family: "Lusitana", weight: "bold", style: "normal", file: f("Lusitana-Bold.ttf") },
  "marcellus": { label: "Marcellus (serif)", family: "Marcellus", weight: "normal", style: "normal", file: f("Marcellus-Regular.ttf") },
  "marcellussc": { label: "Marcellus SC (serif)", family: "Marcellus SC", weight: "normal", style: "normal", file: f("MarcellusSC-Regular.ttf") },
  "martel-bold": { label: "Martel Bold (serif)", family: "Martel", weight: "bold", style: "normal", file: f("Martel-Bold.ttf") },
  "neuton-bold": { label: "Neuton Bold (serif)", family: "Neuton", weight: "bold", style: "normal", file: f("Neuton-Bold.ttf") },
  "noticiatext-bold": { label: "Noticia Text Bold (serif)", family: "Noticia Text", weight: "bold", style: "normal", file: f("NoticiaText-Bold.ttf") },
  "odormeanchey": { label: "Odor Mean Chey (serif)", family: "Odor Mean Chey", weight: "normal", style: "normal", file: f("OdorMeanChey-Regular.ttf") },
  "oflsortsmillgoudytt": { label: "OFL Sorts Mill Goudy TT (serif)", family: "OFL Sorts Mill Goudy TT", weight: "normal", style: "normal", file: f("OFLGoudyStMTT.ttf") },
  "oldstandardtt-bold": { label: "Old Standard TT Bold (serif)", family: "Old Standard TT", weight: "bold", style: "normal", file: f("OldStandard-Bold.ttf") },
  "ovo": { label: "Ovo (serif)", family: "Ovo", weight: "normal", style: "normal", file: f("Ovo-Regular.ttf") },
  "playfairdisplaysc-bold": { label: "Playfair Display SC Bold (serif)", family: "Playfair Display SC", weight: "bold", style: "normal", file: f("PlayfairDisplaySC-Bold.ttf") },
  "prata": { label: "Prata (serif)", family: "Prata", weight: "normal", style: "normal", file: f("Prata-Regular.ttf") },
  "ptserifcaption": { label: "PT Serif Caption (serif)", family: "PT Serif Caption", weight: "normal", style: "normal", file: f("PT_Serif-Caption-Web-Regular.ttf") },
  "rufina-bold": { label: "Rufina Bold (serif)", family: "Rufina", weight: "bold", style: "normal", file: f("Rufina-Bold.ttf") },
  "slabo27px": { label: "Slabo 27px (serif)", family: "Slabo 27px", weight: "normal", style: "normal", file: f("Slabo27px-Regular.ttf") },
  "sortsmillgoudy": { label: "Sorts Mill Goudy (serif)", family: "Sorts Mill Goudy", weight: "normal", style: "normal", file: f("SortsMillGoudy-Regular.ttf") },
  "suwannaphum-bold": { label: "Suwannaphum Bold (serif)", family: "Suwannaphum", weight: "bold", style: "normal", file: f("Suwannaphum-Bold.ttf") },
  "thabit-bold": { label: "Thabit Bold (serif)", family: "Thabit", weight: "bold", style: "normal", file: f("Thabit-Bold.ttf") },
  "tienne-bold": { label: "Tienne Bold (serif)", family: "Tienne", weight: "bold", style: "normal", file: f("Tienne-Bold.ttf") },
  "tinos-bold": { label: "Tinos Bold (serif)", family: "Tinos", weight: "bold", style: "normal", file: f("Tinos-Bold.ttf") },
  "trirong-bold": { label: "Trirong Bold (serif)", family: "Trirong", weight: "bold", style: "normal", file: f("Trirong-Bold.ttf") },
  "unna-bold": { label: "Unna Bold (serif)", family: "Unna", weight: "bold", style: "normal", file: f("Unna-Bold.ttf") },
  "zillaslab-bold": { label: "Zilla Slab Bold (serif)", family: "Zilla Slab", weight: "bold", style: "normal", file: f("ZillaSlab-Bold.ttf") },

  // ---------------- More: Display / decorative ----------------
  "angkor": { label: "Angkor (display)", family: "Angkor", weight: "normal", style: "normal", file: f("Angkor-Regular.ttf") },
  "astloch-bold": { label: "Astloch Bold (display)", family: "Astloch", weight: "bold", style: "normal", file: f("Astloch-Bold.ttf") },
  "audiowide": { label: "Audiowide (display)", family: "Audiowide", weight: "normal", style: "normal", file: f("Audiowide-Regular.ttf") },
  "bangers": { label: "Bangers (display)", family: "Bangers", weight: "normal", style: "normal", file: f("Bangers-Regular.ttf") },
  "battambang-bold": { label: "Battambang Bold (display)", family: "Battambang", weight: "bold", style: "normal", file: f("Battambang-Bold.ttf") },
  "bigshotone": { label: "Bigshot One (display)", family: "Bigshot One", weight: "normal", style: "normal", file: f("BigshotOne-Regular.ttf") },
  "blackopsone": { label: "Black Ops One (display)", family: "Black Ops One", weight: "normal", style: "normal", file: f("BlackOpsOne-Regular.ttf") },
  "bokor": { label: "Bokor (display)", family: "Bokor", weight: "normal", style: "normal", file: f("Bokor-Regular.ttf") },
  "bowlbyone": { label: "Bowlby One (display)", family: "Bowlby One", weight: "normal", style: "normal", file: f("BowlbyOne-Regular.ttf") },
  "buda": { label: "Buda (display)", family: "Buda", weight: "normal", style: "normal", file: f("Buda-Light.ttf") },
  "cabinsketch-bold": { label: "Cabin Sketch Bold (display)", family: "Cabin Sketch", weight: "bold", style: "normal", file: f("CabinSketch-Bold.ttf") },
  "carterone": { label: "Carter One (display)", family: "Carter One", weight: "normal", style: "normal", file: f("CarterOne.ttf") },
  "changaone": { label: "Changa One (display)", family: "Changa One", weight: "normal", style: "normal", file: f("ChangaOne-Regular.ttf") },
  "coda": { label: "Coda (display)", family: "Coda", weight: "normal", style: "normal", file: f("Coda-Regular.ttf") },
  "concertone": { label: "Concert One (display)", family: "Concert One", weight: "normal", style: "normal", file: f("ConcertOne-Regular.ttf") },
  "corben-bold": { label: "Corben Bold (display)", family: "Corben", weight: "bold", style: "normal", file: f("Corben-Bold.ttf") },
  "creepster": { label: "Creepster (display)", family: "Creepster", weight: "normal", style: "normal", file: f("Creepster-Regular.ttf") },
  "dangrek": { label: "Dangrek (display)", family: "Dangrek", weight: "normal", style: "normal", file: f("Dangrek-Regular.ttf") },
  "freehand": { label: "Freehand (display)", family: "Freehand", weight: "normal", style: "normal", file: f("Freehand-Regular.ttf") },
  "fugazone": { label: "Fugaz One (display)", family: "Fugaz One", weight: "normal", style: "normal", file: f("FugazOne-Regular.ttf") },
  "gruppo": { label: "Gruppo (display)", family: "Gruppo", weight: "normal", style: "normal", file: f("Gruppo-Regular.ttf") },
  "kenia": { label: "Kenia (display)", family: "Kenia", weight: "normal", style: "normal", file: f("Kenia-Regular.ttf") },
  "koulen": { label: "Koulen (display)", family: "Koulen", weight: "normal", style: "normal", file: f("Koulen-Regular.ttf") },
  "lilitaone": { label: "Lilita One (display)", family: "Lilita One", weight: "normal", style: "normal", file: f("LilitaOne-Regular.ttf") },
  "lilyscriptone": { label: "Lily Script One (display)", family: "Lily Script One", weight: "normal", style: "normal", file: f("LilyScriptOne-Regular.ttf") },
  "medievalsharp": { label: "MedievalSharp (display)", family: "MedievalSharp", weight: "normal", style: "normal", file: f("MedievalSharp.ttf") },
  "megrim": { label: "Megrim (display)", family: "Megrim", weight: "normal", style: "normal", file: f("Megrim.ttf") },
  "metal": { label: "Metal (display)", family: "Metal", weight: "normal", style: "normal", file: f("Metal-Regular.ttf") },
  "miltonian": { label: "Miltonian (display)", family: "Miltonian", weight: "normal", style: "normal", file: f("Miltonian-Regular.ttf") },
  "miltoniantattoo": { label: "Miltonian Tattoo (display)", family: "Miltonian Tattoo", weight: "normal", style: "normal", file: f("MiltonianTattoo-Regular.ttf") },
  "monoton": { label: "Monoton (display)", family: "Monoton", weight: "normal", style: "normal", file: f("Monoton-Regular.ttf") },
  "moul": { label: "Moul (display)", family: "Moul", weight: "normal", style: "normal", file: f("Moul-Regular.ttf") },
  "novacut": { label: "Nova Cut (display)", family: "Nova Cut", weight: "normal", style: "normal", file: f("NovaCut.ttf") },
  "novaflat": { label: "Nova Flat (display)", family: "Nova Flat", weight: "normal", style: "normal", file: f("NovaFlat.ttf") },
  "novaoval": { label: "Nova Oval (display)", family: "Nova Oval", weight: "normal", style: "normal", file: f("NovaOval.ttf") },
  "novaround": { label: "Nova Round (display)", family: "Nova Round", weight: "normal", style: "normal", file: f("NovaRound.ttf") },
  "novascript": { label: "Nova Script (display)", family: "Nova Script", weight: "normal", style: "normal", file: f("NovaScript-Regular.ttf") },
  "novaslim": { label: "Nova Slim (display)", family: "Nova Slim", weight: "normal", style: "normal", file: f("NovaSlim.ttf") },
  "novasquare": { label: "Nova Square (display)", family: "Nova Square", weight: "normal", style: "normal", file: f("NovaSquare.ttf") },
  "oleoscript-bold": { label: "Oleo Script Bold (display)", family: "Oleo Script", weight: "bold", style: "normal", file: f("OleoScript-Bold.ttf") },
  "patuaone": { label: "Patua One (display)", family: "Patua One", weight: "normal", style: "normal", file: f("PatuaOne-Regular.ttf") },
  "pressstart2p": { label: "Press Start 2P (display)", family: "Press Start 2P", weight: "normal", style: "normal", file: f("PressStart2P-Regular.ttf") },
  "rammettoone": { label: "Rammetto One (display)", family: "Rammetto One", weight: "normal", style: "normal", file: f("RammettoOne-Regular.ttf") },
  "shrikhand": { label: "Shrikhand (display)", family: "Shrikhand", weight: "normal", style: "normal", file: f("Shrikhand-Regular.ttf") },
  "sigmarone": { label: "Sigmar One (display)", family: "Sigmar One", weight: "normal", style: "normal", file: f("SigmarOne-Regular.ttf") },
  "smythe": { label: "Smythe (display)", family: "Smythe", weight: "normal", style: "normal", file: f("Smythe-Regular.ttf") },
  "sniglet": { label: "Sniglet (display)", family: "Sniglet", weight: "normal", style: "normal", file: f("Sniglet-Regular.ttf") },
  "squadaone": { label: "Squada One (display)", family: "Squada One", weight: "normal", style: "normal", file: f("SquadaOne-Regular.ttf") },
  "staatliches": { label: "Staatliches (display)", family: "Staatliches", weight: "normal", style: "normal", file: f("Staatliches-Regular.ttf") },
  "taprom": { label: "Taprom (display)", family: "Taprom", weight: "normal", style: "normal", file: f("Taprom-Regular.ttf") },
  "titanone": { label: "Titan One (display)", family: "Titan One", weight: "normal", style: "normal", file: f("TitanOne-Regular.ttf") },
  "unifrakturcook-bold": { label: "UnifrakturCook Bold (display)", family: "UnifrakturCook", weight: "bold", style: "normal", file: f("UnifrakturCook-Bold.ttf") },
  "unifrakturmaguntia": { label: "UnifrakturMaguntia (display)", family: "UnifrakturMaguntia", weight: "normal", style: "normal", file: f("UnifrakturMaguntia-Book.ttf") },
  "wallpoet": { label: "Wallpoet (display)", family: "Wallpoet", weight: "normal", style: "normal", file: f("Wallpoet-Regular.ttf") },
  "yesevaone": { label: "Yeseva One (display)", family: "Yeseva One", weight: "normal", style: "normal", file: f("YesevaOne-Regular.ttf") },

  // ---------------- More: Script / handwriting ----------------
  "alexbrush": { label: "Alex Brush (script)", family: "Alex Brush", weight: "normal", style: "normal", file: f("AlexBrush-Regular.ttf") },
  "annieuseyourtelescope": { label: "Annie Use Your Telescope (script)", family: "Annie Use Your Telescope", weight: "normal", style: "normal", file: f("AnnieUseYourTelescope-Regular.ttf") },
  "architectsdaughter": { label: "Architects Daughter (script)", family: "Architects Daughter", weight: "normal", style: "normal", file: f("ArchitectsDaughter-Regular.ttf") },
  "arizonia": { label: "Arizonia (script)", family: "Arizonia", weight: "normal", style: "normal", file: f("Arizonia-Regular.ttf") },
  "badscript": { label: "Bad Script (script)", family: "Bad Script", weight: "normal", style: "normal", file: f("BadScript-Regular.ttf") },
  "berkshireswash": { label: "Berkshire Swash (script)", family: "Berkshire Swash", weight: "normal", style: "normal", file: f("BerkshireSwash-Regular.ttf") },
  "bilboswashcaps": { label: "Bilbo Swash Caps (script)", family: "Bilbo Swash Caps", weight: "normal", style: "normal", file: f("BilboSwashCaps-Regular.ttf") },
  "cedarvillecursive": { label: "Cedarville Cursive (script)", family: "Cedarville Cursive", weight: "normal", style: "normal", file: f("Cedarville-Cursive.ttf") },
  "chilanka": { label: "Chilanka (script)", family: "Chilanka", weight: "normal", style: "normal", file: f("Chilanka-Regular.ttf") },
  "coveredbyyourgrace": { label: "Covered By Your Grace (script)", family: "Covered By Your Grace", weight: "normal", style: "normal", file: f("CoveredByYourGrace.ttf") },
  "dawningofanewday": { label: "Dawning of a New Day (script)", family: "Dawning of a New Day", weight: "normal", style: "normal", file: f("DawningofaNewDay.ttf") },
  "delius": { label: "Delius (script)", family: "Delius", weight: "normal", style: "normal", file: f("Delius-Regular.ttf") },
  "deliusswashcaps": { label: "Delius Swash Caps (script)", family: "Delius Swash Caps", weight: "normal", style: "normal", file: f("DeliusSwashCaps-Regular.ttf") },
  "gaegu-bold": { label: "Gaegu Bold (script)", family: "Gaegu", weight: "bold", style: "normal", file: f("Gaegu-Bold.ttf") },
  "giveyouglory": { label: "Give You Glory (script)", family: "Give You Glory", weight: "normal", style: "normal", file: f("GiveYouGlory.ttf") },
  "gloriahallelujah": { label: "Gloria Hallelujah (script)", family: "Gloria Hallelujah", weight: "normal", style: "normal", file: f("GloriaHallelujah.ttf") },
  "gochihand": { label: "Gochi Hand (script)", family: "Gochi Hand", weight: "normal", style: "normal", file: f("GochiHand-Regular.ttf") },
  "herrvonmuellerhoff": { label: "Herr Von Muellerhoff (script)", family: "Herr Von Muellerhoff", weight: "normal", style: "normal", file: f("HerrVonMuellerhoff-Regular.ttf") },
  "italianno": { label: "Italianno (script)", family: "Italianno", weight: "normal", style: "normal", file: f("Italianno-Regular.ttf") },
  "itim": { label: "Itim (script)", family: "Itim", weight: "normal", style: "normal", file: f("Itim-Regular.ttf") },
  "justmeagaindownhere": { label: "Just Me Again Down Here (script)", family: "Just Me Again Down Here", weight: "normal", style: "normal", file: f("JustMeAgainDownHere.ttf") },
  "kaushanscript": { label: "Kaushan Script (script)", family: "Kaushan Script", weight: "normal", style: "normal", file: f("KaushanScript-Regular.ttf") },
  "kristi": { label: "Kristi (script)", family: "Kristi", weight: "normal", style: "normal", file: f("Kristi-Regular.ttf") },
  "labelleaurore": { label: "La Belle Aurore (script)", family: "La Belle Aurore", weight: "normal", style: "normal", file: f("LaBelleAurore.ttf") },
  "leaguescript": { label: "League Script (script)", family: "League Script", weight: "normal", style: "normal", file: f("LeagueScript-Regular.ttf") },
  "leckerlione": { label: "Leckerli One (script)", family: "Leckerli One", weight: "normal", style: "normal", file: f("LeckerliOne-Regular.ttf") },
  "lovedbytheking": { label: "Loved by the King (script)", family: "Loved by the King", weight: "normal", style: "normal", file: f("LovedbytheKing.ttf") },
  "mali-bold": { label: "Mali Bold (script)", family: "Mali", weight: "bold", style: "normal", file: f("Mali-Bold.ttf") },
  "meddon": { label: "Meddon (script)", family: "Meddon", weight: "normal", style: "normal", file: f("Meddon.ttf") },
  "mrdafoe": { label: "Mr Dafoe (script)", family: "Mr Dafoe", weight: "normal", style: "normal", file: f("MrDafoe-Regular.ttf") },
  "mrssaintdelafield": { label: "Mrs Saint Delafield (script)", family: "Mrs Saint Delafield", weight: "normal", style: "normal", file: f("MrsSaintDelafield-Regular.ttf") },
  "neucha": { label: "Neucha (script)", family: "Neucha", weight: "normal", style: "normal", file: f("Neucha.ttf") },
  "niconne": { label: "Niconne (script)", family: "Niconne", weight: "normal", style: "normal", file: f("Niconne-Regular.ttf") },
  "norican": { label: "Norican (script)", family: "Norican", weight: "normal", style: "normal", file: f("Norican-Regular.ttf") },
  "nothingyoucoulddo": { label: "Nothing You Could Do (script)", family: "Nothing You Could Do", weight: "normal", style: "normal", file: f("NothingYouCouldDo.ttf") },
  "overtherainbow": { label: "Over the Rainbow (script)", family: "Over the Rainbow", weight: "normal", style: "normal", file: f("OvertheRainbow.ttf") },
  "pangolin": { label: "Pangolin (script)", family: "Pangolin", weight: "normal", style: "normal", file: f("Pangolin-Regular.ttf") },
  "petitformalscript": { label: "Petit Formal Script (script)", family: "Petit Formal Script", weight: "normal", style: "normal", file: f("PetitFormalScript-Regular.ttf") },
  "reeniebeanie": { label: "Reenie Beanie (script)", family: "Reenie Beanie", weight: "normal", style: "normal", file: f("ReenieBeanie.ttf") },
  "rougescript": { label: "Rouge Script (script)", family: "Rouge Script", weight: "normal", style: "normal", file: f("RougeScript-Regular.ttf") },
  "shortstack": { label: "Short Stack (script)", family: "Short Stack", weight: "normal", style: "normal", file: f("ShortStack-Regular.ttf") },
  "sofia": { label: "Sofia (script)", family: "Sofia", weight: "normal", style: "normal", file: f("Sofia-Regular.ttf") },
  "sriracha": { label: "Sriracha (script)", family: "Sriracha", weight: "normal", style: "normal", file: f("Sriracha-Regular.ttf") },
  "stylescript": { label: "Style Script (script)", family: "Style Script", weight: "normal", style: "normal", file: f("StyleScript-Regular.ttf") },
  "sueellenfrancisco": { label: "Sue Ellen Francisco (script)", family: "Sue Ellen Francisco", weight: "normal", style: "normal", file: f("SueEllenFrancisco-Regular.ttf") },
  "swankyandmoomoo": { label: "Swanky and Moo Moo (script)", family: "Swanky and Moo Moo", weight: "normal", style: "normal", file: f("SwankyandMooMoo.ttf") },
  "thegirlnextdoor": { label: "The Girl Next Door (script)", family: "The Girl Next Door", weight: "normal", style: "normal", file: f("TheGirlNextDoor.ttf") },
  "vibur": { label: "Vibur (script)", family: "Vibur", weight: "normal", style: "normal", file: f("Vibur-Regular.ttf") },
  "waitingforthesunrise": { label: "Waiting for the Sunrise (script)", family: "Waiting for the Sunrise", weight: "normal", style: "normal", file: f("WaitingfortheSunrise.ttf") },
  "zeyada": { label: "Zeyada (script)", family: "Zeyada", weight: "normal", style: "normal", file: f("Zeyada.ttf") },

  // ---------------- More: Monospace ----------------
  "anonymouspro-bold": { label: "Anonymous Pro Bold (monospace)", family: "Anonymous Pro", weight: "bold", style: "normal", file: f("AnonymousPro-Bold.ttf") },
  "cousine-bold": { label: "Cousine Bold (monospace)", family: "Cousine", weight: "bold", style: "normal", file: f("Cousine-Bold.ttf") },
  "cutivemono": { label: "Cutive Mono (monospace)", family: "Cutive Mono", weight: "normal", style: "normal", file: f("CutiveMono-Regular.ttf") },
  "digitalnumbers": { label: "Digital Numbers (monospace)", family: "Digital Numbers", weight: "normal", style: "normal", file: f("DigitalNumbers-Regular.ttf") },
  "dmmono": { label: "DM Mono (monospace)", family: "DM Mono", weight: "normal", style: "normal", file: f("DMMono-Regular.ttf") },
  "firamono-bold": { label: "Fira Mono Bold (monospace)", family: "Fira Mono", weight: "bold", style: "normal", file: f("FiraMono-Bold.ttf") },
  "ibmplexmono-bold": { label: "IBM Plex Mono Bold (monospace)", family: "IBM Plex Mono", weight: "bold", style: "normal", file: f("IBMPlexMono-Bold.ttf") },
  "lekton-bold": { label: "Lekton Bold (monospace)", family: "Lekton", weight: "bold", style: "normal", file: f("Lekton-Bold.ttf") },
  "majormonodisplay": { label: "Major Mono Display (monospace)", family: "Major Mono Display", weight: "normal", style: "normal", file: f("MajorMonoDisplay-Regular.ttf") },
  "monofett": { label: "Monofett (monospace)", family: "Monofett", weight: "normal", style: "normal", file: f("Monofett-Regular.ttf") },
  "novamono": { label: "Nova Mono (monospace)", family: "Nova Mono", weight: "normal", style: "normal", file: f("NovaMono.ttf") },
  "oxygenmono": { label: "Oxygen Mono (monospace)", family: "Oxygen Mono", weight: "normal", style: "normal", file: f("OxygenMono-Regular.ttf") },
  "ptmono": { label: "PT Mono (monospace)", family: "PT Mono", weight: "normal", style: "normal", file: f("PTM55FT.ttf") },
  "sharetechmono": { label: "Share Tech Mono (monospace)", family: "Share Tech Mono", weight: "normal", style: "normal", file: f("ShareTechMono-Regular.ttf") },
  "vt323": { label: "VT323 (monospace)", family: "VT323", weight: "normal", style: "normal", file: f("VT323-Regular.ttf") },
};

const DEFAULT_FONT_KEY = "poppins-bold";

function getFont(key) {
  return FONTS[key] || FONTS[DEFAULT_FONT_KEY];
}

function listFonts() {
  return Object.entries(FONTS).map(([key, font]) => ({
    key,
    label: font.label,
    family: font.family,
    weight: font.weight,
    style: font.style,
  }));
}

module.exports = { FONTS, DEFAULT_FONT_KEY, getFont, listFonts, FONT_DIR };
